/**
 * Unified error codes for structured API error responses.
 *
 * Format: UPPER_SNAKE_CASE, grouped by domain.
 * Every code must have a corresponding human-readable message in the throw site
 * or in a shared message map.
 *
 * Usage:
 *   throw new AppException(ErrorCode.USER_NOT_FOUND, 'User not found', 404);
 */

export const ErrorCode = {
  // ── Auth ──────────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_DISABLED: 'AUTH_USER_DISABLED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  AUTH_SETUP_ALREADY_COMPLETED: 'AUTH_SETUP_ALREADY_COMPLETED',
  AUTH_SETUP_IN_PROGRESS: 'AUTH_SETUP_IN_PROGRESS',
  AUTH_MFA_UNAVAILABLE: 'AUTH_MFA_UNAVAILABLE',
  AUTH_SSO_ENFORCED: 'AUTH_SSO_ENFORCED',

  // ── User ──────────────────────────────────────────────
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',

  // ── Workspace ─────────────────────────────────────────
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',

  // ── Space ─────────────────────────────────────────────
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  SPACE_SLUG_EXISTS: 'SPACE_SLUG_EXISTS',

  // ── Page ──────────────────────────────────────────────
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  PARENT_PAGE_NOT_FOUND: 'PARENT_PAGE_NOT_FOUND',
  PAGE_INVALID_MOVE_POSITION: 'PAGE_INVALID_MOVE_POSITION',
  PAGE_MOVE_CYCLE: 'PAGE_MOVE_CYCLE',
  PAGE_MOVE_NAME_CONFLICT: 'PAGE_MOVE_NAME_CONFLICT',

  // ── Sidebar Category ─────────────────────────────────
  SIDEBAR_CATEGORY_LIMIT_EXCEEDED: 'SIDEBAR_CATEGORY_LIMIT_EXCEEDED',
  SIDEBAR_CATEGORY_NAME_DUPLICATED: 'SIDEBAR_CATEGORY_NAME_DUPLICATED',
  SIDEBAR_CATEGORY_NOT_FOUND: 'SIDEBAR_CATEGORY_NOT_FOUND',
  SIDEBAR_CATEGORIES_NOT_FOUND: 'SIDEBAR_CATEGORIES_NOT_FOUND',
  SIDEBAR_CATEGORY_REORDER_INVALID: 'SIDEBAR_CATEGORY_REORDER_INVALID',
  CATEGORY_SPACE_MISMATCH: 'CATEGORY_SPACE_MISMATCH',
  ROOT_NODE_ONLY_CATEGORY_ASSIGNMENT: 'ROOT_NODE_ONLY_CATEGORY_ASSIGNMENT',

  // ── Share ─────────────────────────────────────────────
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_EXPIRED: 'SHARE_EXPIRED',
  SHARE_PASSWORD_REQUIRED: 'SHARE_PASSWORD_REQUIRED',
  SHARE_PASSWORD_INVALID: 'SHARE_PASSWORD_INVALID',
  SHARE_ACCESS_TOKEN_INVALID: 'SHARE_ACCESS_TOKEN_INVALID',
  SHARE_ACCESS_MODE_FORBIDDEN: 'SHARE_ACCESS_MODE_FORBIDDEN',
  SHARE_TTL_INVALID: 'SHARE_TTL_INVALID',
  SHARE_REGENERATE_REQUIRED: 'SHARE_REGENERATE_REQUIRED',
  SHARE_VERIFY_RATE_LIMITED: 'SHARE_VERIFY_RATE_LIMITED',

  // ── Editor Session ───────────────────────────────────
  EDITOR_SESSION_CONFLICT: 'EDITOR_SESSION_CONFLICT',
  EDITOR_SESSION_FORBIDDEN: 'EDITOR_SESSION_FORBIDDEN',
  EDITOR_SESSION_RESOURCE_NOT_FOUND: 'EDITOR_SESSION_RESOURCE_NOT_FOUND',

  // ── Migration ────────────────────────────────────────
  MIGRATION_ALREADY_RUNNING: 'MIGRATION_ALREADY_RUNNING',

  // ── Generic ──────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
